spring:
  profiles: pro
  datasource:
    url: jdbc:mysql://47.96.125.85:3306/topshow?useSSL=false&characterEncoding=UTF-8
    username: topshow
    password: M81oPdMtc
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      max-idle: 20
      max-active: 20
      initial-size: 5
      test-while-idle: true
  redis:
    port: 6379
    host: 47.96.125.85
    password: NE1Ik4aEm1I1Br8aYJ0nwPV
    database: 1
    timeout: 5000ms

swagger:
  show: true
